### ISSUE TITLE
Date format?

### ISSUE THREAD

**Issue by tu6619** [ipcortex/FAC-FMC#58]
How should we format the date for each call? At the moment we're using the postgresql TimeStamp but it doesn't appear possible to make any comparison with it in our tests. Is the postgresql timestamp what you guys are generally used to using?

**Comment by rjp44** [comment]
Would suggest parsing it into a JS Date object which you will need for comparison in filters and also reformatted any way you need to for display. Apart from anything else postgres timestamp will be UTC and you will need local time for display. Let me see if we have conversion code sitting around somewhere internally.

**Comment by rjp44** [comment]
SELECT EXTRACT(EPOCH FROM TIMESTAMP  date_column) FROM table ...
into JS variable epochDate which will contain decimal number of seconds since 00:00 01-01-1970
then construct a new Date object with integer number of milliseconds (seconds * 1000) since epoch
var date = new Date(epochDate * 1000);
Not tested any of the above, but may work

**Comment by rjp44** [comment]
Sorry, did test it and SQL error, should be:
SELECT EXTRACT(EPOCH FROM date_column) AS new_colum_name FROM table ...

**Comment by rjp44** [comment]
Steve just asked me if you are talking about an actual postresql timestamp you are pulling out of a database, or the string we return from the REST call. If it is the former then my advise stands, If it is the latter then that should be in a string form that you can pass directly to the Date() constructor to get it parsed.

**Comment by tu6619** [comment]
thanks for your help, it was indeed the former!
